services:
  samurai_plapo_sv:
    build:
      target: dev
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
#    depends_on:
#      - postgres

#    postgres:
#      image: postgres:latest
#      ports:
#          - "5432:5432"
#      environment:
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_DB: samurai_plapo_db
#      volumes:
#          - postgres_data:/var/lib/postgresql/data
#
#
#  volumes:
#    postgres_data:
