services:
  samurai_plapo_sv:
    build:
      target: dev
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-samurai_plapo}
      MYSQL_USER: ${MYSQL_USER:-samurai_plapo}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-samurai_plapo}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
