openapi: 3.0.0
info:
  title: Samurai Plapo API
  version: 1.0.0
servers:
  - url: http://localhost:8000

paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The user ID.
      responses:
        '201':
          description: User created
        '400':
          description: Invalid request
  /rooms:
    post:
      summary: Create a new room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The room name.
      responses:
        '201':
          description: Room created
        '400':
          description: Invalid request
  /rooms/{roomId}/users:
    post:
      summary: Add a user to a room
      parameters:
        - in: path
          name: roomId
          schema:
            type: integer
          required: true
          description: The ID of the room.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: The user ID.
      responses:
        '201':
          description: User added to room
        '400':
          description: Invalid request
  /votes:
    post:
      summary: Create a new vote
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: The user ID.
                roomId:
                  type: integer
                  description: The room ID.
                estimatedPoint:
                  type: integer
                  description: The estimated point (Fibonacci number).
      responses:
        '201':
          description: Vote created
        '400':
          description: Invalid request
